version: "3.3"
# Staging only
services:

  web:
    build: 
      context: ./web
      dockerfile: ./docker/prodRDS/Dockerfile
    volumes:
      - ./web:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./web/docker/prodRDS/.prod
    command: "python manage.py runserver 0.0.0.0:8000"
    restart: always
