version: "3.9"
# Dev only
services:

  web:
    build: 
      context: ./web
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ./web:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./web/docker/dev/.dev
    command: "python manage.py runserver 0.0.0.0:8000"
    networks:
      vpcbr:
        ipv4_address: 192.168.137.203

    restart: always

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.137.0/24
         gateway: 192.168.137.1