# Generated by Django 3.2 on 2022-09-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user'),
        ('numberLottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberlottery',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountNumberLottery', to='account.account'),
        ),
    ]
